FROM jsreport/jsreport:1.8.2
MAINTAINER Jan Blaha
EXPOSE 5488

RUN apt-get update && \
    apt-get install -y build-essential python3-dev python3-pip python3-cffi libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info && \
    pip3 install --upgrade pip && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/apt/*

RUN pip3 install WeasyPrint 

RUN mkdir -p /usr/src/app/node_modules/jsreport-weasyprint-pdf
WORKDIR /usr/src/app/node_modules/jsreport-weasyprint-pdf

COPY package.json /usr/src/app/node_modules/jsreport-weasyprin-pdft
RUN npm install && \
    npm cache clean -f

COPY . /usr/src/app/node_modules/jsreport-weasyprint-pdf

WORKDIR /usr/src/app

ENV scripts_allowedModules *

CMD ["bash", "/usr/src/app/run.sh"]